version: '3.7'
services:
  app:
    container_name: stun
    depends_on:
      - letsencrypt
    network_mode: host
    build:
      network: host
      dockerfile: ./Dockerfile
      context: ./
    env_file:
      - .env
    restart: always
    environment:
      externalip: ${EXTERNALIP}
      user: ${USER}
      password: ${PASSWORD}
      realm: ${REALM}
    
    ports: 
    - '${EXTERNALIP:-0.0.0.0}:3478:3478'
    - '${EXTERNALIP:-0.0.0.0}:3478:3478/udp'
    - '${EXTERNALIP:-0.0.0.0}:5349:5349'
    - '${EXTERNALIP:-0.0.0.0}:5349:5349/udp'
    - '${EXTERNALIP:-0.0.0.0}:49152:49152/udp'
    volumes:
      - ${CERTDIR}:/certs
      - ./logs:/logs
  letsencrypt:
    image: nginx:stable
    container_name: stun_nginx
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_NETWORK=${NETWORK:-webproxy}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: ${NETWORK:-webproxy}
