version: '3.7'
services:
  coturn:
    network_mode: host
    build:
      network: host
      dockerfile: ./Dockerfile
      context: ./
    env_file:
      - .env
    restart: always
    container_name: stun
    ports: 
    - '3478:3478'
    - '3478:3478/udp'
    - '5349:5349'
    - '5349:5349/udp'
    - '49152:49152/udp'