version: '3.7'
services:
  app:
    container_name: stunturn
    depends_on:
      - letsencrypt
    network_mode: host
    build:
      network: host
      dockerfile: ./Dockerfile
      context: ./
    image: stunturn
    env_file:
      - .env
    restart: always
    environment:
      externalip: ${EXTERNALIP}
      user: ${USER}
      password: ${PASSWORD}
      realm: ${REALM}
      whattostart: ${WHATTOSTART}
      port: ${PORT}
      tlslisteningport: ${TLSLISTENINGPORT}
      minport: ${MINPORT}
      maxport: ${MAXPORT}
    
    ports: 
    - '${EXTERNALIP:-0.0.0.0}:${PORT}:${PORT}'
    - '${EXTERNALIP:-0.0.0.0}:${PORT}:${PORT}/udp'
    - '${EXTERNALIP:-0.0.0.0}:${TLSLISTENINGPORT}:${TLSLISTENINGPORT}'
    - '${EXTERNALIP:-0.0.0.0}:${TLSLISTENINGPORT}:${TLSLISTENINGPORT}/udp'
    - '${EXTERNALIP:-0.0.0.0}:${MINPORT}-${MAXPORT}:${MINPORT}-${MAXPORT}/udp'
    volumes:
      - ${CERTDIR}:/certs
      - ./logs:/logs
  letsencrypt:
    image: nginx:stable
    container_name: stunturn_nginx
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_NETWORK=${NETWORK:-webproxy}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL=${EMAIL}
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: ${NETWORK:-webproxy}
